// <auto-generated />
using System;
using EcoBridge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoBridgeAPI.Migrations
{
    [DbContext(typeof(EcoBridgeDbContext))]
    partial class EcoBridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoBridge.Domains.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Admin", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Charity", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountId");

                    b.ToTable("Charities");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("VolunteerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharityId");

                    b.HasIndex("DonorId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Donor", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("UserType")
                        .HasColumnType("tinyint");

                    b.HasKey("AccountId");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Volunteer", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleDetails")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountId");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Admin", b =>
                {
                    b.HasOne("EcoBridge.Domains.Models.Account", "Account")
                        .WithOne("Admin")
                        .HasForeignKey("EcoBridge.Domains.Models.Admin", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Charity", b =>
                {
                    b.HasOne("EcoBridge.Domains.Models.Account", "Account")
                        .WithOne("Charity")
                        .HasForeignKey("EcoBridge.Domains.Models.Charity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Donation", b =>
                {
                    b.HasOne("EcoBridge.Domains.Models.Charity", "Charity")
                        .WithMany("Donations")
                        .HasForeignKey("CharityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcoBridge.Domains.Models.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoBridge.Domains.Models.Volunteer", "Volunteer")
                        .WithMany("Donations")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Charity");

                    b.Navigation("Donor");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Donor", b =>
                {
                    b.HasOne("EcoBridge.Domains.Models.Account", "Account")
                        .WithOne("Donor")
                        .HasForeignKey("EcoBridge.Domains.Models.Donor", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Volunteer", b =>
                {
                    b.HasOne("EcoBridge.Domains.Models.Account", "Account")
                        .WithOne("Volunteer")
                        .HasForeignKey("EcoBridge.Domains.Models.Volunteer", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Account", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Charity");

                    b.Navigation("Donor");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Charity", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Donor", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("EcoBridge.Domains.Models.Volunteer", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
